# Generated by Django 3.0.6 on 2021-03-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tvshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(default='', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_no', models.IntegerField()),
                ('pub_date', models.DateField()),
                ('episode_no', models.IntegerField()),
                ('episode_link', models.CharField(max_length=200)),
                ('tv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshows.Tvshow')),
            ],
        ),
    ]
