# Generated by Django 3.0.6 on 2021-03-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0002_auto_20210327_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='trailer_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
