# Generated by Django 3.0.6 on 2021-03-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0003_tvshow_trailer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
