# Generated by Django 3.0.6 on 2021-03-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0004_tvshow_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='year',
            field=models.CharField(default='', max_length=50),
        ),
    ]
