# Generated by Django 3.0.6 on 2021-03-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=200)),
                ('year', models.CharField(default='', max_length=50)),
                ('likes', models.CharField(default='', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(default='', upload_to='img')),
                ('magnet_link', models.CharField(default='', max_length=1000)),
                ('trailer_link', models.CharField(default='', max_length=1000)),
                ('category', models.CharField(default='', max_length=100)),
                ('Hindi', models.BooleanField(default=False)),
                ('English', models.BooleanField(default=False)),
            ],
        ),
    ]
