# Generated by Django 3.0.6 on 2021-03-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210322_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
