# Generated by Django 3.0.6 on 2021-03-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
