# Generated by Django 3.0.6 on 2021-03-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_upcoming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='magnet_link',
            new_name='magnet_link_1080p',
        ),
        migrations.AddField(
            model_name='movie',
            name='magnet_link_720p',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
