# Generated by Django 3.0.6 on 2021-03-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_upcoming'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpComing',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tvshow',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='upcoming',
        ),
    ]
