# Generated by Django 3.0.6 on 2021-04-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webname', models.CharField(max_length=200)),
                ('weblink', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
